*&---------------------------------------------------------------------*
*& Include          ZBMM0040_C01
*&---------------------------------------------------------------------*

CLASS LCL_EVENT_HANDLER DEFINITION.
  PUBLIC SECTION.
    CLASS-METHODS:
      ON_BUTTON_CLICK FOR EVENT BUTTON_CLICK OF CL_GUI_ALV_GRID
        IMPORTING ES_ROW_NO ES_COL_ID,

      ON_TOOLBAR2 FOR EVENT TOOLBAR OF CL_GUI_ALV_GRID
        IMPORTING E_OBJECT,

      ON_USER_COMMAND2 FOR EVENT USER_COMMAND OF CL_GUI_ALV_GRID
        IMPORTING E_UCOMM.

ENDCLASS.

CLASS LCL_EVENT_HANDLER IMPLEMENTATION.

  METHOD ON_BUTTON_CLICK.
    READ TABLE GT_DISPLAY1 INTO GS_DISPLAY1 INDEX ES_ROW_NO-ROW_ID.

    CASE ES_COL_ID-FIELDNAME.
      WHEN 'ADD'.
        PERFORM ADD_PRMAT. " '추가'버튼 클릭 시.
      WHEN 'DEL'.
        PERFORM DEL_PRMAT. " '차감'버튼 클릭 시.
    ENDCASE.
  ENDMETHOD.

  METHOD ON_TOOLBAR2.
    PERFORM HANDLE_TOOLBAR2 USING E_OBJECT.
  ENDMETHOD.

  METHOD ON_USER_COMMAND2.
    PERFORM HANDLE_USER_COMMAND2 USING E_UCOMM.
  ENDMETHOD.

ENDCLASS.
